import { TEST_IMAGES } from '@/config/testImages';

export const mockClothingItems = [
  {
    id: '1',
    userId: '1',
    name: 'Stylish Top',
    category: 'tops',
    subcategory: 'blouse',
    brand: 'Fashion Brand',
    color: { primary: 'Multi' },
    season: ['spring', 'summer', 'fall'],
    occasion: ['casual', 'work', 'date'],
    size: 'M',
    images: {
      original: TEST_IMAGES.image1,
      processed: TEST_IMAGES.image1,
      thumbnail: TEST_IMAGES.image1,
    },
    tags: ['trendy', 'versatile'],
    wearCount: 8,
    lastWorn: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
    isFavorite: true,
    notes: 'Perfect for multiple occasions',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: '1',
    name: 'Classic Piece',
    category: 'tops',
    subcategory: 'shirt',
    brand: 'Designer Label',
    color: { primary: 'Neutral' },
    season: ['spring', 'summer', 'fall', 'winter'],
    occasion: ['work', 'formal', 'casual'],
    size: 'M',
    images: {
      original: TEST_IMAGES.image2,
      processed: TEST_IMAGES.image2,
      thumbnail: TEST_IMAGES.image2,
    },
    tags: ['classic', 'essential'],
    wearCount: 12,
    lastWorn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
    isFavorite: true,
    notes: 'Wardrobe staple',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: '1',
    name: 'Summer Outfit',
    category: 'dresses',
    subcategory: 'casual_dress',
    brand: 'Trendy Co',
    color: { primary: 'Colorful' },
    season: ['spring', 'summer'],
    occasion: ['casual', 'vacation', 'brunch'],
    size: 'M',
    images: {
      original: TEST_IMAGES.image3,
      processed: TEST_IMAGES.image3,
      thumbnail: TEST_IMAGES.image3,
    },
    tags: ['summer', 'comfortable'],
    wearCount: 6,
    lastWorn: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
    isFavorite: false,
    notes: 'Great for warm weather',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Original items with real images
  {
    id: '4',
    userId: '1',
    name: 'Black T-Shirt',
    category: 'tops',
    subcategory: 't-shirt',
    brand: 'Uniqlo',
    color: { primary: 'Black' },
    season: ['spring', 'summer', 'fall', 'winter'],
    occasion: ['casual', 'lounge'],
    size: 'M',
    images: {
      original: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=600&fit=crop',
      processed: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=600&fit=crop',
      thumbnail: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=150&h=150&fit=crop',
    },
    tags: ['basic', 'essential'],
    wearCount: 15,
    lastWorn: null,
    isActive: true,
    isFavorite: true,
    notes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: '1',
    name: 'Blue Jeans',
    category: 'bottoms',
    subcategory: 'jeans',
    brand: "Levi's",
    color: { primary: 'Blue' },
    season: ['spring', 'summer', 'fall', 'winter'],
    occasion: ['casual', 'work'],
    size: 'M',
    images: {
      original: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=600&fit=crop',
      processed: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=600&fit=crop',
      thumbnail: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=150&h=150&fit=crop',
    },
    tags: ['denim', 'essential'],
    wearCount: 20,
    lastWorn: null,
    isActive: true,
    isFavorite: true,
    notes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];